DROP TABLE IF EXISTS REQUEST_LOGS;

CREATE TABLE REQUEST_LOGS (
  id INT AUTO_INCREMENT  PRIMARY KEY,
  name VARCHAR(250) NOT NULL,
  email VARCHAR(250) NOT NULL,
  address VARCHAR(250) NOT NULL,
  request_timestamp DATE NOT NULL
);